server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tqt?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
mybatis:
  type-aliases-package: com.yaorange.tqt.pojo
  configuration:
    map-underscore-to-camel-case: true
